services:
  testamdo:
    container_name: testamdo
    build: ./testamdo
    ports:
      - "3000:3000"
    env_file:
      - ./testamdo/.env
    volumes:
      - testamdo-volume:/var/www/html

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env
    volumes:
      - frontend-volume:/var/www/html

  nginx:
    container_name: nginx-server
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - frontend-volume:/var/www/html
    depends_on:
      - frontend

volumes:
  frontend-volume:
