services:
  frontend:
    container_name: spa-frontend
    build: ./frontend
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env
    volumes:
      - spa-volume:/var/www/html

  cc-nginx:
    container_name: nginx-server
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - spa-volume:/var/www/html
    depends_on:
      - frontend

volumes:
  spa-volume:
